version: "3.8" 

services:
  maa-client:
    build: 
      context: ./maa-client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - maa-network
    depends_on:
      - maa-server

  maa-server:
    build: 
      context: ./maa-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - maa-network
    environment:
      - NODE_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root.123
      - MYSQL_DATABASE=maanetdb
      - MYSQL_HOST=maanet-mysql
      - MYSQL_PORT=3306
    command: npm run start:dev
    user: node
    depends_on:
      maanet-db:
        condition: service_healthy
    restart: on-failure

  maanet-db:
    container_name: maanet-mysql
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Root.123
      - MYSQL_DATABASE=maanetdb
      - MYSQL_PASSWORD=Root.123
    ports:
      - "3306:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - maa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pRoot.123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

networks:
  maa-network:
    driver: bridge
    name: maa-network

volumes:
  mysql_data:
    name: maanet-mysql-data